import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

// ─── CLI argument parsing ────────────────────────────────────────────

function parseArgs(args: string[]): { outputDir: string; diagramPath: string } {
  let outputDir = "dist";
  let diagramPath = "diagram.json";

  for (let i = 0; i < args.length; i++) {
    if ((args[i] === "--output" || args[i] === "-o") && args[i + 1]) {
      outputDir = args[++i];
    } else if ((args[i] === "--diagram" || args[i] === "-d") && args[i + 1]) {
      diagramPath = args[++i];
    } else if (args[i] === "--help" || args[i] === "-h") {
      console.log(`
Usage: npm run build:static -- [options]

Options:
  -o, --output <dir>      Output directory (default: "dist")
  -d, --diagram <file>    Path to diagram.json (default: "diagram.json")
  -h, --help              Show this help message

Examples:
  npm run build:static -- --output ./diagram
  npm run build:static -- -o ./docs/architecture -d ./my-diagram.json
`);
      process.exit(0);
    }
  }

  return { outputDir, diagramPath };
}

// ─── Main ────────────────────────────────────────────────────────────

const SKILL_DIR = path.resolve(import.meta.dirname, "..");
const INLINE_DATA_PATH = path.join(SKILL_DIR, "src", "lib", "inline-data.ts");

const DEFAULT_CONTENT = `// This file is the default (dev/serve mode) version.
// During a static build, scripts/build-static.ts overwrites this file
// with the diagram JSON string, then restores it after the build.
export const INLINE_DIAGRAM_JSON: string | null = null;
`;

function main() {
  const { outputDir, diagramPath } = parseArgs(process.argv.slice(2));

  // Resolve paths relative to cwd (not skill dir)
  const resolvedDiagramPath = path.resolve(diagramPath);
  const resolvedOutputDir = path.resolve(outputDir);

  // 1. Validate diagram file exists
  if (!fs.existsSync(resolvedDiagramPath)) {
    console.error(`Error: diagram file not found: ${resolvedDiagramPath}`);
    process.exit(1);
  }

  // 2. Validate diagram file is non-empty
  const diagramJson = fs.readFileSync(resolvedDiagramPath, "utf-8").trim();
  if (!diagramJson) {
    console.error("Error: diagram file is empty");
    process.exit(1);
  }

  // 3. Validate diagram file is valid JSON
  try {
    const parsed = JSON.parse(diagramJson);
    if (!parsed.nodes || !Array.isArray(parsed.nodes) || parsed.nodes.length === 0) {
      console.error("Error: diagram must have at least one node in the 'nodes' array");
      process.exit(1);
    }
  } catch (e) {
    console.error(`Error: diagram file is not valid JSON: ${e instanceof Error ? e.message : e}`);
    process.exit(1);
  }

  console.log(`Diagram:  ${resolvedDiagramPath}`);
  console.log(`Output:   ${resolvedOutputDir}/`);

  // 4. Overwrite inline-data.ts with the diagram content
  //    JSON.stringify wraps the JSON string in quotes and escapes internal quotes,
  //    producing a valid TS string literal containing the raw JSON.
  const escapedJson = JSON.stringify(diagramJson);
  const injectedContent = `// AUTO-GENERATED by build-static.ts — do not edit\nexport const INLINE_DIAGRAM_JSON: string | null = ${escapedJson};\n`;

  fs.writeFileSync(INLINE_DATA_PATH, injectedContent);

  try {
    // 5. Run vite build with output directory override
    const result = spawnSync("npx", ["vite", "build", "--base", "./", "--outDir", resolvedOutputDir], {
      cwd: SKILL_DIR,
      stdio: "inherit",
      env: { ...process.env, DIAGRAM_STATIC: "1" },
    });

    if (result.status !== 0) {
      process.exit(result.status ?? 1);
    }

    console.log(`\nStatic diagram exported to: ${resolvedOutputDir}/`);
    console.log("Open index.html in a browser to view the diagram.");
  } finally {
    // 6. ALWAYS restore inline-data.ts to default (even on build failure)
    fs.writeFileSync(INLINE_DATA_PATH, DEFAULT_CONTENT);
  }
}

main();
